version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    env_file:
      - .env
    ports:
      - 12345:3306
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

  # restaurant-service:
  #   build: ./
  #   container_name: restaurant-service
  #   env_file:
  #     - .env
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - mysql

