version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-restaurant-service
    env_file:
      - .env
    ports:
      - ${RESTAURANT_SERVICE_MYSQL_PORT}:${RESTAURANT_SERVICE_MYSQL_PORT}
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - humf-service-network

  restaurant-service:
    build: ./
    image: restaurant-service:1.0
    container_name: restaurant-service
    env_file:
      - .env
    ports:
      - ${RESTAURANT_SERVICE_PORT}:${RESTAURANT_SERVICE_PORT}
    depends_on:
      - mysql
    command: npm run start:dev
    networks:
      - humf-service-network

networks:
  humf-service-network:
    name: humf-service-network
    external: false

volumes:
  mysql_data:
    name: mysql_data
    external: false
